### ISSUE TITLE
10.1.600 - Epicor Customization (Test) - startIndex cannot be larger than length of string

### ISSUE THREAD

**Issue by HallSimonHall** [josegomez/epicor-editor#1]
Attempting to use the Test option on a customization on ABC Maintenance threw the following exception.

Title of the Dialog was Error during loading themes.
![image](https://user-images.githubusercontent.com/48973539/55046839-efccbe80-5096-11e9-952b-79280449cc27.png)

-----------------------------------------------------------
Application Error

Exception caught in: mscorlib

Error Detail 
============
Message: startIndex cannot be larger than length of string.
Parameter name: startIndex
Program: CommonLanguageRuntimeLibrary
Method: Substring

Client Stack Trace 
==================
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ice.Lib.Styling.canThemesBeApplied(Session session)
   at Ice.Lib.Styling.LoadThemeByConfiguration(Object Sender)
---------------------------------------------------------------------

Client form opens correctly with the customization.

**Comment by josegomez** [comment]
Can you tell me which form? And if possible can you send me a copy of the customixation

**Comment by HallSimonHall** [comment]
Jose,
I think I messed up these issues sorry,  I both this and the #2 We get the Error Loading themes.  In #2  We also get the additional error if you cancel out of the customization selection form before loading the form.  Issue #2 relates to the ABC Entry form (ABC Code Maintenance: Material Management>Inventory Management>setup>ABC Code

**Comment by josegomez** [comment]
@HallSimonHall  published a new version upgrade the extension in VS Code and download a new copy of the DLL's. Let me know if this works better. Removed the Edit, Launch and Debug functionality from VS that was all moved to the ToolBox. Let me know if you are still having the issues. 
If that's the case I need a copy of the customization, PM it to me in e10help if you want.

**Comment by josegomez** [comment]
@HallSimonHall  I believe this is fixed in the latest version. Please confirm, you'll have to update the extension to version > 0.0.43 and download the latest helper.
