### ISSUE TITLE
Use Extension Settings For Folder Paths As Opposed To CustomizationInfo.json

### ISSUE THREAD

**Issue by gingerhelp** [josegomez/epicor-editor#12]
Putting this out as an issue, but I will help out with a PR.  Here is the scenario - we have a big project where lots of devs from various companies are working on customizations so we have set up a company-specific GitHub repository to track everything.  Initially when I set up the repository for them I gitignored everything but Script.cs and the customization XML files but later put those back in so that users freshly checking out the repository could still run the customizations.  The challenge is that if developer A has her Epicor Customizations folder setup differently in the extension settings than developer B, developer B will get some invalid path issues when he goes to work on a customization because the paths get baked into CustomizationInfo.json:

![image](https://user-images.githubusercontent.com/51887706/66578418-0f19cd80-eb49-11e9-9fa2-62fffd74f2d7.png)

The suggestion for this reported issue is that we replace the various spots in the extensions where values are derived from CustomizationInfo.json to the extension settings.  For example:

VS Code extension line 89 currently:
```
argsAry.push(String(customSettings.Folder));
```

VS Code extension line 89 proposed:
* Disclaimer, I have not tested this - just my assumption based on reading the code
```
argsAry.push(config.get("epicor.customizationfolder"));
```

In a multi-developer environment it would be ideal if the data sorted in CustomizationInfo.json was base bones with any environmental settings (client location, user credentials, etc) stored in settings.

**Comment by josegomez** [comment]
I'm out till Monday but I'll take a look

**Comment by gingerhelp** [comment]
Closing this out just to clean up open issues.  This VSCode plugin is deprecated in favor of the full Visual Studio version.
