### ISSUE TITLE
10.1.600 - Epicor Customization (Edit Controls) Exception

### ISSUE THREAD

**Issue by HallSimonHall** [josegomez/epicor-editor#2]
Related to #1  
But also Get an exception. If you cancel before clicking ok to the customization.

![image](https://user-images.githubusercontent.com/48973539/55047064-8b5e2f00-5097-11e9-9ee9-8b87c108bf2b.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ice.Lib.Framework.EpiViewUtils.OnUpdate(EpiTransaction trans, EpiDataView view, IEpiAdapterLink link, Boolean displayExceptions)
   at Ice.Lib.Framework.EpiSingleViewTransaction.OnUpdate()
   at Erp.UI.App.AbcCodeEntry.AbcCodeForm.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CustomizationEditor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Epicor/Test/Client/CustomizationEditor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Ice.Core.Session
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Core.Session.DLL
----------------------------------------
Ice.Lib.Deployment
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.Deployment.DLL
----------------------------------------
CommandLine
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0
    CodeBase: file:///C:/Epicor/Test/Client/CommandLine.DLL
----------------------------------------
CommonClasses
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Epicor/Test/Client/CommonClasses.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CommonForms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Epicor/Test/Client/CommonForms.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Ice.Lib.EpiClientLib
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.25
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.EpiClientLib.DLL
----------------------------------------
Ice.Lib.Startup
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.Startup.DLL
----------------------------------------
Epicor
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.25
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.EXE
----------------------------------------
Epicor.ServiceModel
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.ServiceModel.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Epicor.Ice.Version
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.25
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.Ice.Version.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Ice.Contracts.Lib.SessionMod
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.Lib.SessionMod.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
Ice.Lib.AppSettingsHandler
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.AppSettingsHandler.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
Ice.Lib.Cryptography
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.Cryptography.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    Assembly Version: 4.0.0.0
    Win32 Version: 14.0.23107.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.Data.DataSetExtensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.DataSetExtensions/v4.0_4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3282.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Epicor.App.Version
    Assembly Version: 10.1.600.0
    Win32 Version: 10.1.600.25
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.App.Version.DLL
----------------------------------------
Ice.Contracts.BO.UserFile
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.BO.UserFile.DLL
----------------------------------------
Ice.Lib.EpiResourceLib
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.25
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.EpiResourceLib.DLL
----------------------------------------
Infragistics4.Win.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.v12.2.DLL
----------------------------------------
Ice.Lib.ClientPlugins
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.ClientPlugins.DLL
----------------------------------------
Erp.Lib.ErpPlugins
    Assembly Version: 10.1.600.0
    Win32 Version: 10.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Plugins/Erp.Lib.ErpPlugins.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Ice.Lib.Styling
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.Styling.DLL
----------------------------------------
Ice.Lib.ServerStartup
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.ServerStartup.DLL
----------------------------------------
Ice.Contracts.Lib.BOReader
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.Lib.BOReader.DLL
----------------------------------------
Ice.Contracts.BO.LangTran
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.BO.LangTran.DLL
----------------------------------------
Infragistics4.Win.UltraWinEditors.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinEditors.v12.2.DLL
----------------------------------------
Infragistics4.Shared.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Shared.v12.2.DLL
----------------------------------------
Infragistics4.Win.Misc.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.Misc.v12.2.DLL
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
Ice.Lib.EpiResourceLib.resources
    Assembly Version: 3.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Ice.Lib.EpiResourceLib.resources.DLL
----------------------------------------
Ice.Lib.Styling.resources
    Assembly Version: 3.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Ice.Lib.Styling.resources.DLL
----------------------------------------
Ice.Lib.BroadcastTower
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.BroadcastTower.DLL
----------------------------------------
Ice.Lib.EpiClientLib.resources
    Assembly Version: 3.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Ice.Lib.EpiClientLib.resources.DLL
----------------------------------------
Infragistics4.Win.UltraWinToolbars.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinToolbars.v12.2.DLL
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Infragistics4.Win.UltraWinGrid.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinGrid.v12.2.DLL
----------------------------------------
Infragistics4.Win.UltraWinTree.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinTree.v12.2.DLL
----------------------------------------
Epicor.Diagnostics
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.Diagnostics.DLL
----------------------------------------
Epicor.Ice.Tasks
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.Ice.Tasks.DLL
----------------------------------------
Ice.Contracts.Lib.ClassAttribute
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.Lib.ClassAttribute.DLL
----------------------------------------
Ice.Lib.FWCombos
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.FWCombos.DLL
----------------------------------------
Ice.UI.CustomizationMaintEntry
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.UI.CustomizationMaintEntry.DLL
----------------------------------------
Ice.Contracts.BO.QuickSearch
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.BO.QuickSearch.DLL
----------------------------------------
Ice.Contracts.BO.Menu
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.BO.Menu.DLL
----------------------------------------
Ice.Contracts.BO.GenXData
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.BO.GenXData.DLL
----------------------------------------
Ice.Adapters.GenXData
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.25
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Adapters.GenXData.DLL
----------------------------------------
Ice.Adapters.Menu
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Adapters.Menu.DLL
----------------------------------------
Ice.Adapters.UserFile
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Adapters.UserFile.DLL
----------------------------------------
Ice.Contracts.Lib.ClientCache
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Contracts.Lib.ClientCache.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452
    CodeBase: file:///C:/Epicor/Test/Client/ICSharpCode.SharpZipLib.DLL
----------------------------------------
Infragistics4.Win.UltraWinStatusBar.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinStatusBar.v12.2.DLL
----------------------------------------
Infragistics4.Win.UltraWinDock.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinDock.v12.2.DLL
----------------------------------------
Infragistics4.Win.UltraWinMaskedEdit.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinMaskedEdit.v12.2.DLL
----------------------------------------
Ice.UI.CustomizationMaintEntry.resources
    Assembly Version: 3.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Ice.UI.CustomizationMaintEntry.resources.DLL
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Ice.Adapters.GenXData.resources
    Assembly Version: 3.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Ice.Adapters.GenXData.resources.DLL
----------------------------------------
Ice.Lib.GlobalStrings
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Ice.Lib.GlobalStrings.DLL
----------------------------------------
Ice.Lib.GlobalStrings.resources
    Assembly Version: 3.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Ice.Lib.GlobalStrings.resources.DLL
----------------------------------------
Epicor.Ice.Shared.Social
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Epicor.Ice.Shared.Social.DLL
----------------------------------------
Erp.UI.AbcCodeEntry
    Assembly Version: 10.1.600.0
    Win32 Version: 10.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Erp.UI.AbcCodeEntry.DLL
----------------------------------------
Erp.Adapters.ABCCode
    Assembly Version: 10.1.600.0
    Win32 Version: 10.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Erp.Adapters.ABCCode.DLL
----------------------------------------
Erp.Contracts.BO.ABCCode
    Assembly Version: 10.1.600.0
    Win32 Version: 10.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Erp.Contracts.BO.ABCCode.DLL
----------------------------------------
Erp.UI.AbcCodeEntry.resources
    Assembly Version: 10.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Erp.UI.AbcCodeEntry.resources.DLL
----------------------------------------
Erp.Lib.GlobalStrings
    Assembly Version: 10.1.600.0
    Win32 Version: 10.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/Erp.Lib.GlobalStrings.DLL
----------------------------------------
Erp.Lib.GlobalStrings.resources
    Assembly Version: 10.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Erp.Lib.GlobalStrings.resources.DLL
----------------------------------------
Erp.Contracts.BO.ABCCode.resources
    Assembly Version: 10.1.600.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Epicor/Test/Client/en-AU/Erp.Contracts.BO.ABCCode.resources.DLL
----------------------------------------
SetUserObjectsLimit
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/SetUserObjectsLimit.EXE
----------------------------------------
VisualStudioDebugHelper
    Assembly Version: 3.1.600.0
    Win32 Version: 3.1.600.0
    CodeBase: file:///C:/Epicor/Test/Client/VisualStudioDebugHelper.DLL
----------------------------------------
Infragistics4.Win.UltraWinListView.v12.2
    Assembly Version: 12.2.20122.2018
    Win32 Version: 12.2.20122.2018
    CodeBase: file:///C:/Epicor/Test/Client/Infragistics4.Win.UltraWinListView.v12.2.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by josegomez** [comment]
Can you tell me which form?

**Comment by HallSimonHall** [comment]
Just firing up the laptop...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by HallSimonHall** [comment]
The form was ABC maintenance.  
[App.AbcCodeEntry.AbcCodeForm_Customization_Test_VSCode_CustomExport.zip](https://github.com/josegomez/epicor-editor/files/3012685/App.AbcCodeEntry.AbcCodeForm_Customization_Test_VSCode_CustomExport.zip)

**Comment by HallSimonHall** [comment]
Jose,
I tried replicating this issue with other customizations and I cant.  Here is a video replicating it on the ABC form.  Let me know if you need any more information.
![2019-03-27_22-01-27](https://user-images.githubusercontent.com/48973539/55071178-f893b380-50db-11e9-9417-e2d90d8dae66.gif)

**Comment by josegomez** [comment]
Got it @HallSimonHall  let me check on that I moved most of that functionality to the Toolbox. Do you get the same issue if you Edit from the ToolBox?
