### ISSUE TITLE
Visual Studio Code now broken

### ISSUE THREAD

**Issue by Pants44** [josegomez/epicor-editor#20]
Looks like the reference to "ms-vscode.csharp" is now broken for new installs. I believe it should point to "ms-dotnettools.csharp"

**Comment by Pants44** [comment]
#21

**Comment by josegomez** [comment]
Correct I am not maintaining the vscode version is just not good enough for complex C# projects. Visual Studio Regular is the one that I'm keeping up.

**Comment by josegomez** [comment]
https://marketplace.visualstudio.com/items?itemName=josecgomez.EpicorCustomizationEditorVS

**Comment by Pants44** [comment]
I figured that was the case. Just didn't see that being indicated anywhere.

Thanks
