### ISSUE TITLE
Add suport for Kinetic 2021.1

### ISSUE THREAD

**Issue by mclavero1987** [josegomez/epicor-editor#27]
![imagen](https://user-images.githubusercontent.com/60621962/150373444-4f0aeb90-e17d-4bf4-8d35-338d56093c51.png)

![imagen](https://user-images.githubusercontent.com/60621962/150373314-d1c09d9a-a893-4e54-9ad0-7fff94aef5e5.png)

**Comment by josegomez** [comment]
No sporto Visual Studio Code, la version actual es solo para visual studio (normal)

https://github.com/josegomez/epicor-editor-helper

**Comment by mclavero1987** [comment]
Que tal Jose, gracias por tu respuesta. Que pena que se haya quedado fuera VSCode .. vengo usando tu extensión en VSCode junto con  GIT, Azure DEVOPS y Code Stream y va de maravilla.. pude agilizar mucho la manera de realizar las customizaciones en Epicor. Muy buen aporte de tu parte!. Voy a ver si me paso a Visual Studio así la sigo usando.. muchas gracias!
