### ISSUE TITLE
Determine TargetFrameworkVersion in csproj

### ISSUE THREAD

**Issue by stephenb927** [josegomez/epicor-editor#3]
More of a feature request than an issue. We have DLLs that are targeted at greater framework versions than 4.6.1 in some of our customizations. As the assemblies are being retrieved for a particular customization, could the targetframework version in the csproj file be set based on those assemblies. I can change it manually, but I have to do it after every download or resync.

**Comment by josegomez** [comment]
Which version of Epicor? I can move those specifically but I have to keep 4.6.1 for anything in 10.1.500, 600 I don't think 4.7 is supported in those.

**Comment by stephenb927** [comment]
We’re currently on 10.2.200.latest

**Comment by josegomez** [comment]
This has been fixed in the latest version. We determine the "MAX" target framework by looking at all dependencies.
