### ISSUE TITLE
Login Form does not retain credentials or SSO checkbox when remember credentials checked

### ISSUE THREAD

**Issue by HallSimonHall** [josegomez/epicor-editor#6]
It appears that the Environment parameter does persist, if you check the remember credentials, however it does not retain the remember credentials or the SSO boxes as checked or the user credential fields (not sure if you would want the Username and Password to persist if not SSO).

![image](https://user-images.githubusercontent.com/48973539/55390754-96c3c580-5583-11e9-8e2f-b49e42189c87.png)

This is an image of the Login form opening the second time after selecting the environment, SSO and Remember Credentials.

**Comment by josegomez** [comment]
This has been fixed in the latest version.
