### ISSUE TITLE
Edit / Run Without Updating Customization

### ISSUE THREAD

**Issue by gingerhelp** [josegomez/epicor-editor#9]
Jose,

This is an incredible piece of work.  I am working with a team that has had repeated issues of developers stepping on each others toes causing work to get lost using the old "save as another name while you are working on it" approach.  I have presented the idea of using this approach for all customization maintenance and everybody is pretty excited about the idea.  I think the only challenge I've had a bit of difficulty getting my head around centers around how doing a 'Edit / View' actually updates the customization within Epicor while the developer might still be working on it.  Here was some notes I scrapped together for them on a possible approach:

---

So it was mentioned in the introduction that we no longer need to rely on customization naming as our versioning logic for Epicor.  It is better to keep common, consistent names so that the full history of code changes are documented within GitHub.  I am very open to suggestions here keeping in mind the primary objectives:

- The commit history for a customization should remain intact (changing customization names can cause a problem here).

- The loss of work is the primary concern that brought us into this conversation in the first place - that should be prioritized above all else.

- Developers should not have to perform an undue amount of work to publish a version of code that includes enhancements made by others.

- Testers should not have to jump through unreasonable hoops to test their work but should also be shielded from “in progress” work.

So to that end, the recommendation would be that all screens to be customized have three customizations against them - one named exactly the same as the screen itself (i.e. JobEntry), another named as the screen and suffixed with a “_Dev” (i.e. JobEntry_Dev) and the final having a “_Test” suffix (i.e. JobEntry_Test).  All developers will work against the “_Dev” customization and it will be that customization that will hold all source commit history for the screen.  When a “_Dev” customization is stable and ready to be tested it will overwrite the “_Test” version which will have a special testing menu for the testers to access.  Upon tester approval the “_Test” customization will overwrite the version without any prefix.

Under the scenario developer conflicts will certainly occur and mindful use of both source control and frequent syncs will prevent any loss of work.  In the case where a developer encounters the message regarding a newer customization present that will be their trigger to perform the simple steps to merge:

- Commit the current code to GitHub assuming it is of committable quality.  If it is not to that stage currently the developer can create a branch and commit to that instead.

- Use the download function to allow the other developers code to get pulled in.

- Compare the differences using to what is committed in GitHub to perform an effective merge.

---

What I am wondering is whether it would be feasible to change the behavior of 'Edit / View' to not overwrite the actual customization but instead create a temporary customization that is run and then deleted?

**Comment by josegomez** [comment]
Hi Adam, this is definitely something that can be done. 
However I'm short on time these days, and for my purposes this does what I need.
I will total accept a PR on this though :-), I'll keep it in mind if I get some time though.

Also you should be using the Visual Studio (proper) version not VS Code I haven't really been updating the VS Code extension and although they both use the same library there are some improvements in the Visual Studio Version.
https://marketplace.visualstudio.com/items?itemName=josecgomez.EpicorCustomizationEditorVS

https://github.com/josegomez/epicor-editor-helper

I'm closing this for now but feel free to comment some more if you have other questions issues.

**Comment by gingerhelp** [comment]
Yep - thanks @josegomez I will definitely take a peek at the helper library and work on a PR for it.
